modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="dragon_of_berk"
version="1.0.0"
displayName="Dragon of Berk"
credits="https://discord.gg/KamrrKsM"
displayURL="https://mcreator.net"
authors="by: ZGAMERPLEY, BEN 10000, Caiobb26 and Mateus KhMCreator"

[[dependencies.dragon_of_berk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragon_of_berk]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0]"
    ordering="NONE"
    side="BOTH"


[[dependencies.dragon_of_berk]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dragon_of_berk]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

