modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="dragon_of_berk"
version="1.0.0"
displayName="Dragon of Berk"
credits="https://discord.gg/KamrrKsM"
displayURL="https://mcreator.net"
authors="by: ZGAMERPLEY, BEN 10000, Caiobb26 and DG MateusMCreator"

[[dependencies.dragon_of_berk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragon_of_berk]]
    modId="forge"
    mandatory=true
    versionRange="[45.1.0]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragon_of_berk]]
    modId="Curios API"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragon_of_berk]]
    modId="Geckolib API"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dragon_of_berk]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dragon_of_berk]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

