modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="dragon_of_berk"
version="1.0.0"
displayName="Dragon of Berk"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Mateus Kunz Hippler, MCreator"

[[dependencies.dragon_of_berk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragon_of_berk]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0]"
    ordering="NONE"
    side="BOTH"


[[dependencies.dragon_of_berk]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dragon_of_berk]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

